name: Build Flutter APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0' # Choose appropriate version for your project
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get
      working-directory: cold_day_flutter

    - name: Inject Google Maps API Key
      run: |
        sed -i "s/YOUR_GOOGLE_MAPS_API_KEY_HERE/${{ secrets.MAPS_API_KEY }}/g" android/app/src/main/AndroidManifest.xml
      working-directory: cold_day_flutter

    - name: Build APK
      run: flutter build apk --release
      working-directory: cold_day_flutter

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: cold-day-app-apk
        path: cold_day_flutter/build/app/outputs/flutter-apk/app-release.apk
